### PR TITLE
Survivors of the void update

### PR DESCRIPTION
**Pull request by ookami125**
Updated async-storage depenancy to its new home and added fbjs
Added autoscroll to load all images on a page
Ran all scraper options
committing all new images and images.js

### CODE REVIEW

**Comment by ookami125** [comment]
Just realized this has the issue of skills not being parsed properly so still have to update more.

**Review by mngyuan — COMMENTED** [review]
this is great - thanks so much. I made a few comments, but actually, the main thing is that there's a bit of manual work required which I have yet to document anywhere. I don't like the formatting that comes off the wiki for some of the scaling information, so I usually go in and edit it. 

Could you include some screenshots of the new items, rarity dropdown to make sure they're working? And as always, if you don't have time, I'll take a look soon (I'll have to test on the iOS sim anyway), but just let me know.

Thanks again so much! Exciting.

P.S. nit: I like to `prettier` everything (including the generated `.json`, since it helps me with the aforementioned manual edits) before committing it. I think it should go something like

```bash
./node_modules/bin/prettier --write src/
```

**Comment by mngyuan** [comment]
Oops - I wrote this and just pushed "comment" right before bed without seeing your comment. Do your thing, let me know how it goes.

**Comment by ookami125** [comment]
All good, Let's move this over to https://github.com/mngyuan/ror2Handbook/pull/2 since that's the active pull request for this now, this one broke when I was moving commits around to different branches.

**Pull request closed without merging**
